#!/bin/bash
# vim: ts=2 sts=2 sw=2 et ai

DIR=$(dirname ${BASH_SOURCE[0]})

CLANGXX="$DIR/../bin/clang++"
LIBMEKONG="$DIR/../lib/LLVMMekong@CMAKE_SHARED_LIBRARY_SUFFIX@"
MERTLIB="$DIR/../lib/libmekongrt@CMAKE_STATIC_LIBRARY_SUFFIX@"
MERTINC="$DIR/../include/mekong"

OPTS=()
LDOPTS=()

while [[ $# -ge 1 ]]; do
  case $1 in
    -mekong-model*)
      OPTS+=(-mllvm "$1")
      ;;
    -mekong-pre)
      OPTS+=(-mllvm "$1" -O1 --cuda-device-only -c)
      ;;
    -mekong)
      OPTS+=(-mllvm "$1" -I"$MERTINC")
      LDOPTS+=("$MERTLIB")
      ;;
    *)
      OPTS+=("$1")
      ;;
  esac
  shift
done

CMD=("$CLANGXX" -Xclang -load -Xclang "$LIBMEKONG" --cuda-gpu-arch=sm_30)

for word in "${CMD[@]}" "${OPTS[@]}" "${LDOPTS[@]}"; do
  printf "\"$word\" "
done
printf "\n"

"${CMD[@]}" "${OPTS[@]}" "${LDOPTS[@]}"
