#!/bin/bash
# vim: ts=2 sts=2 sw=2 et ai

DIR=$(dirname ${BASH_SOURCE[0]})

CLANGXX="$DIR/../bin/clang++"
LIBMEKONG="$DIR/../lib/LLVMMekong@CMAKE_SHARED_LIBRARY_SUFFIX@"
MERTLIB="$DIR/../lib/libmekongrt.bc"
MERTINC="$DIR/../include/mekong"

OPTS=()
LDOPTS=()
TRACE=

while [[ $# -ge 1 ]]; do
  case $1 in
    "-##")
      TRACE=yes
      ;;
    "-###")
      OPTS+=("$1")
      TRACE=yes
      ;;
    -mekong-model*)
      OPTS+=(-mllvm "$1")
      ;;
    -mekong-pre)
      OPTS+=(-mllvm "$1" -O1 --cuda-device-only -c)
      ;;
    -mekong)
      OPTS+=(-mllvm "$1" -I"$MERTINC")
      LDOPTS+=("$MERTLIB")
      ;;
    *)
      OPTS+=("$1")
      ;;
  esac
  shift
done

CMD=("$CLANGXX" -Xclang -load -Xclang "$LIBMEKONG" --cuda-gpu-arch=sm_30)

if [[ -n "$TRACE" ]]; then
  for word in "${CMD[@]}" "${OPTS[@]}" "${LDOPTS[@]}"; do
    printf "\"$word\" "
  done
  printf "\n"
fi

"${CMD[@]}" "${OPTS[@]}" "${LDOPTS[@]}"
